version: '3.4'

services:
  stargate.webapiserv.web:
    image: ${DOCKER_REGISTRY-}stargate-webapiserv-web
    build:
      context: .
      dockerfile: src/Stargate.WebApiServ.Web/Dockerfile
    container_name: stargate-webapiserv-web
    depends_on:
      - sqldata
  
  sqldata:
    image: postgres:latest
    container_name: stargate-webapiserv-db
    environment:
      POSTGRES_PASSWORD: PostgreSQL@docker
    ports:
      - "5432"
    restart: always

  adminer:
    image: ${DOCKER_REGISTRY-}adminer
    container_name: stargate-webapiserv-dbadminer
    ports:
      - "8080:8080"
    restart: always
